$updates = @{
    '16680897' = @{ 'CODIGO DEL PLANTEL'='OD01981403'; 'UBICACIÓN FÍSICA'='G-E RAFAEL ANTONIO GONZALEZ'; 'NUEVO EPÓNIMO'='RAFAEL ANTONIO GONZALEZ' }
    '8712754' = @{ 'CODIGO DEL PLANTEL'='OD01981403'; 'UBICACIÓN FÍSICA'='G-E RAFAEL ANTONIO GONZALEZ'; 'NUEVO EPÓNIMO'='RAFAEL ANTONIO GONZALEZ' }
    '12220351' = @{ 'CODIGO DEL PLANTEL'='OD01981403'; 'UBICACIÓN FÍSICA'='G-E RAFAEL ANTONIO GONZALEZ'; 'NUEVO EPÓNIMO'='RAFAEL ANTONIO GONZALEZ' }
    '10241882' = @{ 'CODIGO DEL PLANTEL'='OD01981403'; 'UBICACIÓN FÍSICA'='G-E RAFAEL ANTONIO GONZALEZ'; 'NUEVO EPÓNIMO'='RAFAEL ANTONIO GONZALEZ' }
    '12219708' = @{ 'CODIGO DEL PLANTEL'='OD01981403'; 'UBICACIÓN FÍSICA'='G-E RAFAEL ANTONIO GONZALEZ'; 'NUEVO EPÓNIMO'='RAFAEL ANTONIO GONZALEZ' }
    '13447492' = @{ 'CODIGO DEL PLANTEL'='OD01981403'; 'UBICACIÓN FÍSICA'='G-E RAFAEL ANTONIO GONZALEZ'; 'NUEVO EPÓNIMO'='RAFAEL ANTONIO GONZALEZ' }
    '14447326' = @{ 'CODIGO DEL PLANTEL'='OD01981403'; 'UBICACIÓN FÍSICA'='G-E RAFAEL ANTONIO GONZALEZ'; 'NUEVO EPÓNIMO'='RAFAEL ANTONIO GONZALEZ' }
    '14936633' = @{ 'CODIGO DEL PLANTEL'='OD01981403'; 'UBICACIÓN FÍSICA'='G-E RAFAEL ANTONIO GONZALEZ'; 'NUEVO EPÓNIMO'='RAFAEL ANTONIO GONZALEZ' }
    '28542738' = @{ 'CODIGO DEL PLANTEL'='OD05331403'; 'UBICACIÓN FÍSICA'='NER NUC ESC.RURAL N 340'; 'NUEVO EPÓNIMO'='MANUEL DE JESUS MORA GARCIA' }
    '20832111' = @{ 'CODIGO DEL PLANTEL'='OD05331403'; 'UBICACIÓN FÍSICA'='NER NUC ESC.RURAL N 340'; 'NUEVO EPÓNIMO'='MANUEL DE JESUS MORA GARCIA' }
    '15754847' = @{ 'CODIGO DEL PLANTEL'='OD05331403'; 'UBICACIÓN FÍSICA'='NER NUC ESC.RURAL N 340'; 'NUEVO EPÓNIMO'='MANUEL DE JESUS MORA GARCIA' }
    '18579371' = @{ 'CODIGO DEL PLANTEL'='OD05331403'; 'UBICACIÓN FÍSICA'='NER NUC ESC.RURAL N 340'; 'NUEVO EPÓNIMO'='MANUEL DE JESUS MORA GARCIA' }
    '16201944' = @{ 'CODIGO DEL PLANTEL'='OD11201405'; 'UBICACIÓN FÍSICA'='E.E. EL CURO'; 'NUEVO EPÓNIMO'='MARIA SIXTA CONTRERAS' }
    '20831107' = @{ 'CODIGO DEL PLANTEL'='OD11201405'; 'UBICACIÓN FÍSICA'='E.E. EL CURO'; 'NUEVO EPÓNIMO'='MARIA SIXTA CONTRERAS' }
    '24191432' = @{ 'CODIGO DEL PLANTEL'='OD11201405'; 'UBICACIÓN FÍSICA'='E.E. EL CURO'; 'NUEVO EPÓNIMO'='MARIA SIXTA CONTRERAS' }
    '16654963' = @{ 'CODIGO DEL PLANTEL'='OD11201405'; 'UBICACIÓN FÍSICA'='E.E. EL CURO'; 'NUEVO EPÓNIMO'='MARIA SIXTA CONTRERAS' }
    '19046757' = @{ 'CODIGO DEL PLANTEL'='OD11201405'; 'UBICACIÓN FÍSICA'='E.E. EL CURO'; 'NUEVO EPÓNIMO'='MARIA SIXTA CONTRERAS' }
    '16200143' = @{ 'CODIGO DEL PLANTEL'='OD11201405'; 'UBICACIÓN FÍSICA'='E.E. EL CURO'; 'NUEVO EPÓNIMO'='MARIA SIXTA CONTRERAS' }
    '16316087' = @{ 'CODIGO DEL PLANTEL'='OD11201405'; 'UBICACIÓN FÍSICA'='E.E. EL CURO'; 'NUEVO EPÓNIMO'='MARIA SIXTA CONTRERAS' }
    '20831069' = @{ 'CODIGO DEL PLANTEL'='OD11201405'; 'UBICACIÓN FÍSICA'='E.E. EL CURO'; 'NUEVO EPÓNIMO'='MARIA SIXTA CONTRERAS' }
    '6175543' = @{ 'CODIGO DEL PLANTEL'='ON16261406'; 'UBICACIÓN FÍSICA'='ESCUELA PARA EL EMPRENDIMIENTO ANA MARQUEZ'; 'NUEVO EPÓNIMO'='ANA MARQUEZ' }
    '3764562' = @{ 'CODIGO DEL PLANTEL'='ON16261406'; 'UBICACIÓN FÍSICA'='ESCUELA PARA EL EMPRENDIMIENTO ANA MARQUEZ'; 'NUEVO EPÓNIMO'='ANA MARQUEZ' }
    '10710638' = @{ 'CODIGO DEL PLANTEL'='ON16261406'; 'UBICACIÓN FÍSICA'='ESCUELA PARA EL EMPRENDIMIENTO ANA MARQUEZ'; 'NUEVO EPÓNIMO'='ANA MARQUEZ' }
    '8043959' = @{ 'CODIGO DEL PLANTEL'='ON16261406'; 'UBICACIÓN FÍSICA'='ESCUELA PARA EL EMPRENDIMIENTO ANA MARQUEZ'; 'NUEVO EPÓNIMO'='ANA MARQUEZ' }
    '8022122' = @{ 'CODIGO DEL PLANTEL'='ON16261406'; 'UBICACIÓN FÍSICA'='ESCUELA PARA EL EMPRENDIMIENTO ANA MARQUEZ'; 'NUEVO EPÓNIMO'='ANA MARQUEZ' }
    '10719913' = @{ 'CODIGO DEL PLANTEL'='ON16261406'; 'UBICACIÓN FÍSICA'='ESCUELA PARA EL EMPRENDIMIENTO ANA MARQUEZ'; 'NUEVO EPÓNIMO'='ANA MARQUEZ' }
    '26056887' = @{ 'CODIGO DEL PLANTEL'='OD19090103'; 'UBICACIÓN FÍSICA'='CENTRO DE EDUCACION INICIAL TRIBILIN HUGUITO'; 'NUEVO EPÓNIMO'='TRIBILIN HUGUITO' }
    '25707441' = @{ 'CODIGO DEL PLANTEL'='OD19090103'; 'UBICACIÓN FÍSICA'='CENTRO DE EDUCACION INICIAL TRIBILIN HUGUITO'; 'NUEVO EPÓNIMO'='TRIBILIN HUGUITO' }
    '16444415' = @{ 'CODIGO DEL PLANTEL'='S0922D1408'; 'UBICACIÓN FÍSICA'='CC-JUAN RODRIGUEZ SUAREZ'; 'NUEVO EPÓNIMO'='MAXIMO TORO' }
    '15694623' = @{ 'CODIGO DEL PLANTEL'='OD08291409'; 'UBICACIÓN FÍSICA'='ESCUELA MARTA GARCÍA GARCIA'; 'NUEVO EPÓNIMO'='MARTA GARCÍA GARCIA' }
    '10902022' = @{ 'CODIGO DEL PLANTEL'='OD08321409'; 'UBICACIÓN FÍSICA'='ESCUELA MAXIA FLORINDA ROSALES DE ROMERO'; 'NUEVO EPÓNIMO'='MAXIA FLORINDA ROSALES DE ROMERO' }
    '22987127' = @{ 'CODIGO DEL PLANTEL'='OD13281412'; 'UBICACIÓN FÍSICA'='ESCUELA ELPIDIO BRANDTT MELENDEZ (ANTES ELPIDIO BRANTH)'; 'NUEVO EPÓNIMO'='ELPIDIO BRANDTT MELENDEZ (ANTES ELPIDIO BRANTH)' }
    '11461962' = @{ 'CODIGO DEL PLANTEL'='OD13281412'; 'UBICACIÓN FÍSICA'='ESCUELA ELPIDIO BRANDTT MELENDEZ (ANTES ELPIDIO BRANTH)'; 'NUEVO EPÓNIMO'='ELPIDIO BRANDTT MELENDEZ (ANTES ELPIDIO BRANTH)' }
    '17522063' = @{ 'CODIGO DEL PLANTEL'='OD13281412'; 'UBICACIÓN FÍSICA'='ESCUELA ELPIDIO BRANDTT MELENDEZ (ANTES ELPIDIO BRANTH)'; 'NUEVO EPÓNIMO'='ELPIDIO BRANDTT MELENDEZ (ANTES ELPIDIO BRANTH)' }
    '20847642' = @{ 'CODIGO DEL PLANTEL'='OD13281412'; 'UBICACIÓN FÍSICA'='ESCUELA ELPIDIO BRANDTT MELENDEZ (ANTES ELPIDIO BRANTH)'; 'NUEVO EPÓNIMO'='ELPIDIO BRANDTT MELENDEZ (ANTES ELPIDIO BRANTH)' }
    '19096695' = @{ 'CODIGO DEL PLANTEL'='OD03541414'; 'UBICACIÓN FÍSICA'='GABRIEL MARCIANO PARRA'; 'NUEVO EPÓNIMO'='GABRIEL MARCIANO PARRA' }
    '11224608' = @{ 'CODIGO DEL PLANTEL'='OD03541414'; 'UBICACIÓN FÍSICA'='GABRIEL MARCIANO PARRA'; 'NUEVO EPÓNIMO'='GABRIEL MARCIANO PARRA' }
    '14963608' = @{ 'CODIGO DEL PLANTEL'='OD03541414'; 'UBICACIÓN FÍSICA'='GABRIEL MARCIANO PARRA'; 'NUEVO EPÓNIMO'='GABRIEL MARCIANO PARRA' }
    '24853559' = @{ 'CODIGO DEL PLANTEL'='OD13921417'; 'UBICACIÓN FÍSICA'='ESCUELA VICTORIANO LOBO'; 'NUEVO EPÓNIMO'='VICTORIANO LOBO' }
    '27780727' = @{ 'CODIGO DEL PLANTEL'='OD13921417'; 'UBICACIÓN FÍSICA'='ESCUELA VICTORIANO LOBO'; 'NUEVO EPÓNIMO'='VICTORIANO LOBO' }
    '19042093' = @{ 'CODIGO DEL PLANTEL'='OD13921417'; 'UBICACIÓN FÍSICA'='ESCUELA VICTORIANO LOBO'; 'NUEVO EPÓNIMO'='VICTORIANO LOBO' }
    '20873854' = @{ 'CODIGO DEL PLANTEL'='OD13921417'; 'UBICACIÓN FÍSICA'='ESCUELA VICTORIANO LOBO'; 'NUEVO EPÓNIMO'='VICTORIANO LOBO' }
    '12800271' = @{ 'CODIGO DEL PLANTEL'='OD09601420'; 'UBICACIÓN FÍSICA'='ESCUELA ESTADAL EL GUAMO'; 'NUEVO EPÓNIMO'='EZIO PULIDO ALBORNOZ' }
    '23493717' = @{ 'CODIGO DEL PLANTEL'='OD05041421'; 'UBICACIÓN FÍSICA'='NER 559'; 'NUEVO EPÓNIMO'='AMADOR MORALES MORA' }
}

$csv = Import-Csv "C:\Proyectos\sgh-mr - firebase\migracion\RAC ESTADO MERIDA - PERSONAL ENRIQUECIDO.csv" -Encoding UTF8
foreach ($row in $csv) {
    if ($updates.ContainsKey($row.CEDULA)) {
        $row.'CODIGO DEL PLANTEL' = $updates[$row.CEDULA].'CODIGO DEL PLANTEL'
        $row.'UBICACIÓN FÍSICA' = $updates[$row.CEDULA].'UBICACIÓN FÍSICA'
        $row.'NUEVO EPÓNIMO' = $updates[$row.CEDULA].'NUEVO EPÓNIMO'
    }
}
$csv | Export-Csv "C:\Proyectos\sgh-mr - firebase\migracion\RAC ESTADO MERIDA - PERSONAL ENRIQUECIDO.csv" -NoTypeInformation -Encoding UTF8
Write-Host "44 cedulas reparadas con exito."
